// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BuzzStats.Web.Admin {
	
	
	public partial class TestPage {
		
		protected System.Web.UI.WebControls.CheckBox chkResurrectorMode;
		
		protected System.Web.UI.WebControls.Button btnSetResurrectorMode;
		
		protected System.Web.UI.WebControls.Label lblError;
		
		protected System.Web.UI.WebControls.GridView gvProcessorStatus;
		
		protected System.Web.UI.WebControls.Button btnThrow;
	}
}
