// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.6.57.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BuzzStats.Web {
	
	
	public partial class Charts {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BuzzStats.Web.UserControls.DateRangePicker dateRangePicker;
		
		protected System.Web.UI.WebControls.Button btnRefreshCharts;
	}
}
