name: Publish krt

on:
  push:
    tags: [ "v*" ]

jobs:
  krt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp package --file pom.xml
  krt-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - uses: graalvm/setup-graalvm@v1 # https://github.com/graalvm/setup-graalvm
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build artifact
      run: mvn -B -ntp -Pnative -DskipTests package
    - name: Rename artifact
      run: mv target/krt target/krt-${{ matrix.os }}
    - uses: actions/upload-artifact@v3
      with:
        name: krt-native-image-${{ matrix.os }}
        path: target/krt-${{ matrix.os }}
  krt-native-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - uses: ilammy/msvc-dev-cmd@v1 # https://github.com/ilammy/msvc-dev-cmd
    - uses: graalvm/setup-graalvm@v1 # https://github.com/graalvm/setup-graalvm
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: mvn -B -ntp -Pnative -DskipTests package
    - uses: actions/upload-artifact@v3
      with:
        name: krt-native-image-windows-latest
        path: target/krt.exe
  release:
    runs-on: ubuntu-latest
    needs:
      - krt-native
      - krt-native-windows
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            krt-native-image-macos-latest/krt-macos-latest
            krt-native-image-ubuntu-latest/krt-ubuntu-latest
            krt-native-image-windows-latest/krt.exe
