name: Build $name

on:
  push:
    branches: [ master ]
    paths:
      - $path/**
      - .github/workflows/build-$group-$name.yml
      - pom.xml$extraPaths
  pull_request:
    branches: [ master ]
    paths:
      - $path/**
      - .github/workflows/build-$group-$name.yml
      - pom.xml$extraPaths

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK $javaVersion
      uses: actions/setup-java@v2
      with:
        java-version: '$javaVersion'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: $buildCommand
