name: Release $name

on:
  push:
    tags: [ "$path/v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK $javaVersion
      uses: actions/setup-java@v2
      with:
        java-version: '$javaVersion'
        distribution: 'zulu'
        cache: maven
    - name: Build arturito release tooling
      run: mvn -Pshade -B -ntp -am -pl internal-tooling/arturito clean package
    - name: Run arturito release tooling
      run: >-
        java -jar internal-tooling/arturito/target/arturito-1.0-SNAPSHOT.jar
        --gpg-key
        ${{ secrets.GPG_KEY }}
        --gpg-passphrase
        ${{ secrets.GPG_PASSPHRASE }}
        --nexus-username
        ${{ secrets.OSSRH_USERNAME }}
        --nexus-password
        ${{ secrets.OSSRH_PASSWORD }}
        --path
        $path
