// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BuzzStats.Web {
	
	
	public partial class MasterPage {
		
		protected System.Web.UI.HtmlControls.HtmlHead head;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cpHead;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cphBody;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cphScripts;
	}
}
