//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuzzStats.Web {
    
    
    public partial class Stories {
        
        /// <summary>
        /// litCommentCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litCommentCount;
        
        /// <summary>
        /// storySearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BuzzStats.Web.UserControls.StorySearch storySearch;
        
        /// <summary>
        /// recentlyModifiedStories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BuzzStats.Web.UserControls.StoryList recentlyModifiedStories;
        
        /// <summary>
        /// recentlyCreatedStories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BuzzStats.Web.UserControls.StoryList recentlyCreatedStories;
        
        /// <summary>
        /// recentlyCommentedStories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BuzzStats.Web.UserControls.StoryList recentlyCommentedStories;
    }
}
