/*
 * HangManForm.java
 *
 * Created on August 5, 2004, 7:00 PM
 */

package org.ngss.jhangman;

/**
 * @author ngeor
 */
public class HangManForm extends javax.swing.JFrame {

    /**
     * Creates new form HangManForm.
     */
    public HangManForm() {
        initComponents();

        HangManPanel hmp = new HangManPanel();
        hmp.startGame("Πώς λέγεται η ιδιότητα που επιστρέφει πολλές τιμές;", "Πλειότιμη", "el");
        getContentPane().add(hmp, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }

    /**
     * Exit the Application.
     */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new HangManForm().show();
    }
}
