name: Build zfs-snapshot-trimmer

on:
  push:
    branches: [ master ]
    paths:
      - cli/zfs-snapshot-trimmer/**
      - .github/workflows/build-cli-zfs-snapshot-trimmer.yml
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - cli/zfs-snapshot-trimmer/**
      - .github/workflows/build-cli-zfs-snapshot-trimmer.yml
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp clean verify --file cli/zfs-snapshot-trimmer/pom.xml
