name: Build changes

on:
  push:
    branches: [ master ]
    paths:
      - internal-tooling/changes/**
      - .github/workflows/build-internal-tooling-changes.yml
      - pom.xml
      - libs/cli-parent-pom/**
      - libs/java/**
      - libs/maven-releaser/**
      - libs/yak4j-argparse/**
      - libs/yak4j-dom/**
      - libs/yak4j-git/**
      - libs/yak4j-markdown/**
      - libs/yak4j-maven/**
      - libs/yak4j-process/**
      - libs/yak4j-semver/**
  pull_request:
    branches: [ master ]
    paths:
      - internal-tooling/changes/**
      - .github/workflows/build-internal-tooling-changes.yml
      - pom.xml
      - libs/cli-parent-pom/**
      - libs/java/**
      - libs/maven-releaser/**
      - libs/yak4j-argparse/**
      - libs/yak4j-dom/**
      - libs/yak4j-git/**
      - libs/yak4j-markdown/**
      - libs/yak4j-maven/**
      - libs/yak4j-process/**
      - libs/yak4j-semver/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl internal-tooling/changes -am clean verify
