name: Build yak4j-filename-conventions-maven-plugin

on:
  push:
    branches: [ master ]
    paths:
      - plugins/yak4j-filename-conventions-maven-plugin/**
      - .github/workflows/build-plugins-yak4j-filename-conventions-maven-plugin.yml
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - plugins/yak4j-filename-conventions-maven-plugin/**
      - .github/workflows/build-plugins-yak4j-filename-conventions-maven-plugin.yml
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp clean verify --file plugins/yak4j-filename-conventions-maven-plugin/pom.xml
