name: Build jTetris

on:
  push:
    branches: [ master ]
    paths:
      - gui/jTetris/**
      - .github/workflows/build-gui-jTetris.yml
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - gui/jTetris/**
      - .github/workflows/build-gui-jTetris.yml
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp clean verify --file gui/jTetris/pom.xml
