name: Build yak4j-sync-archetype-maven-plugin

on:
  push:
    branches: [ master ]
    paths:
      - plugins/yak4j-sync-archetype-maven-plugin/**
      - .github/workflows/build-plugins-yak4j-sync-archetype-maven-plugin.yml
      - pom.xml
      - libs/java/**
      - poms/public-library/**
  pull_request:
    branches: [ master ]
    paths:
      - plugins/yak4j-sync-archetype-maven-plugin/**
      - .github/workflows/build-plugins-yak4j-sync-archetype-maven-plugin.yml
      - pom.xml
      - libs/java/**
      - poms/public-library/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl plugins/yak4j-sync-archetype-maven-plugin -am clean verify
