name: Build yak4j-semver

on:
  push:
    branches: [ master ]
    paths:
      - libs/yak4j-semver/**
      - .github/workflows/build-libs-yak4j-semver.yml
      - pom.xml
      - libs/java/**
  pull_request:
    branches: [ master ]
    paths:
      - libs/yak4j-semver/**
      - .github/workflows/build-libs-yak4j-semver.yml
      - pom.xml
      - libs/java/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl libs/yak4j-semver -am clean verify
