name: Build yak4j-xml

on:
  push:
    branches: [ master ]
    paths:
      - libs/yak4j-xml/**
      - .github/workflows/build-libs-yak4j-xml.yml
  pull_request:
    branches: [ master ]
    paths:
      - libs/yak4j-xml/**
      - .github/workflows/build-libs-yak4j-xml.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp verify --file libs/yak4j-xml/pom.xml
