name: Build krt

on:
  push:
    branches: [ master ]
    paths:
      - cli/krt/**
      - .github/workflows/build-cli-krt.yml
      - pom.xml
      - libs/cli-parent-pom/**
      - libs/versions/**
      - poms/java/**
  pull_request:
    branches: [ master ]
    paths:
      - cli/krt/**
      - .github/workflows/build-cli-krt.yml
      - pom.xml
      - libs/cli-parent-pom/**
      - libs/versions/**
      - poms/java/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl cli/krt -am clean verify
