name: Build yak4j-markdown

on:
  push:
    branches: [ master ]
    paths:
      - libs/yak4j-markdown/**
      - .github/workflows/build-libs-yak4j-markdown.yml
      - pom.xml
      - libs/java/**
      - poms/public-library/**
  pull_request:
    branches: [ master ]
    paths:
      - libs/yak4j-markdown/**
      - .github/workflows/build-libs-yak4j-markdown.yml
      - pom.xml
      - libs/java/**
      - poms/public-library/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl libs/yak4j-markdown -am clean verify
