name: Build sifo

on:
  push:
    branches: [ master ]
    paths:
      - internal-tooling/sifo/**
      - .github/workflows/build-internal-tooling-sifo.yml
  pull_request:
    branches: [ master ]
    paths:
      - internal-tooling/sifo/**
      - .github/workflows/build-internal-tooling-sifo.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp verify --file internal-tooling/sifo/pom.xml
