name: Build maven-releaser

on:
  push:
    branches: [ master ]
    paths:
      - libs/maven-releaser/**
      - .github/workflows/build-libs-maven-releaser.yml
      - pom.xml
      - libs/yak4j-dom/**
      - libs/yak4j-maven/**
      - libs/yak4j-process/**
      - libs/yak4j-semver/**
  pull_request:
    branches: [ master ]
    paths:
      - libs/maven-releaser/**
      - .github/workflows/build-libs-maven-releaser.yml
      - pom.xml
      - libs/yak4j-dom/**
      - libs/yak4j-maven/**
      - libs/yak4j-process/**
      - libs/yak4j-semver/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl libs/maven-releaser -am clean verify
