name: Build jDirDiff

on:
  push:
    branches: [ master ]
    paths:
      - gui/jDirDiff/**
      - .github/workflows/build-gui-jDirDiff.yml
  pull_request:
    branches: [ master ]
    paths:
      - gui/jDirDiff/**
      - .github/workflows/build-gui-jDirDiff.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp verify --file gui/jDirDiff/pom.xml
