name: Build yak4j-utc-time-zone-mapper

on:
  push:
    branches: [ master ]
    paths:
      - libs/yak4j-utc-time-zone-mapper/**
      - .github/workflows/build-libs-yak4j-utc-time-zone-mapper.yml
      - pom.xml
      - poms/java/**
      - poms/public-library/**
  pull_request:
    branches: [ master ]
    paths:
      - libs/yak4j-utc-time-zone-mapper/**
      - .github/workflows/build-libs-yak4j-utc-time-zone-mapper.yml
      - pom.xml
      - poms/java/**
      - poms/public-library/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl libs/yak4j-utc-time-zone-mapper -am clean verify
