name: Build krt

on:
  push:
    branches: [ master ]
    paths:
      - cli/krt/**
      - .github/workflows/build-cli-krt.yml
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - cli/krt/**
      - .github/workflows/build-cli-krt.yml
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp clean verify --file cli/krt/pom.xml
