name: Build BuzzStats

on:
  push:
    branches: [ master ]
    paths:
      - web/BuzzStats/**
      - .github/workflows/build-web-BuzzStats.yml
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - web/BuzzStats/**
      - .github/workflows/build-web-BuzzStats.yml
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp clean verify --file web/BuzzStats/pom.xml
