name: Build archetype-quickstart-jdk8

on:
  push:
    branches: [ master ]
    paths:
      - archetypes/archetype-quickstart-jdk8/**
      - .github/workflows/build-archetypes-archetype-quickstart-jdk8.yml
      - pom.xml
      - poms/java/**
      - poms/public-library/**
  pull_request:
    branches: [ master ]
    paths:
      - archetypes/archetype-quickstart-jdk8/**
      - .github/workflows/build-archetypes-archetype-quickstart-jdk8.yml
      - pom.xml
      - poms/java/**
      - poms/public-library/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl archetypes/archetype-quickstart-jdk8 -am clean verify
