name: Build jSpiderGame

on:
  push:
    branches: [ master ]
    paths:
      - gui/jSpiderGame/**
      - .github/workflows/build-gui-jSpiderGame.yml
      - pom.xml
      - libs/java/**
  pull_request:
    branches: [ master ]
    paths:
      - gui/jSpiderGame/**
      - .github/workflows/build-gui-jSpiderGame.yml
      - pom.xml
      - libs/java/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl gui/jSpiderGame -am clean verify
