name: Build BuzzStats

on:
  push:
    branches: [ master ]
    paths:
      - web/BuzzStats/**
      - .github/workflows/build-web-BuzzStats.yml
      - pom.xml
      - poms/java/**
  pull_request:
    branches: [ master ]
    paths:
      - web/BuzzStats/**
      - .github/workflows/build-web-BuzzStats.yml
      - pom.xml
      - poms/java/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl web/BuzzStats -am clean verify
