name: Build sifo

on:
  push:
    branches: [ master ]
    paths:
      - internal-tooling/sifo/**
      - .github/workflows/build-internal-tooling-sifo.yml
      - pom.xml
      - libs/changelog/**
      - libs/cli-parent-pom/**
      - libs/java/**
      - libs/maven-releaser/**
      - libs/versions/**
      - libs/yak4j-dom/**
      - libs/yak4j-git/**
      - libs/yak4j-maven/**
      - libs/yak4j-process/**
  pull_request:
    branches: [ master ]
    paths:
      - internal-tooling/sifo/**
      - .github/workflows/build-internal-tooling-sifo.yml
      - pom.xml
      - libs/changelog/**
      - libs/cli-parent-pom/**
      - libs/java/**
      - libs/maven-releaser/**
      - libs/versions/**
      - libs/yak4j-dom/**
      - libs/yak4j-git/**
      - libs/yak4j-maven/**
      - libs/yak4j-process/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl internal-tooling/sifo -am clean verify
