name: Build arturito

on:
  push:
    branches: [ master ]
    paths:
      - internal-tooling/arturito/**
      - .github/workflows/build-internal-tooling-arturito.yml
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - internal-tooling/arturito/**
      - .github/workflows/build-internal-tooling-arturito.yml
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp -pl internal-tooling/arturito clean verify
