name: Build yak4j-xml

on:
  push:
    branches: [ master ]
    paths:
      - libs/yak4j-xml/**
      - .github/workflows/build-libs-yak4j-xml.yml
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - libs/yak4j-xml/**
      - .github/workflows/build-libs-yak4j-xml.yml
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B -ntp clean verify --file libs/yak4j-xml/pom.xml
