name: Test krt

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  krt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  krt-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - uses: graalvm/setup-graalvm@v1 # https://github.com/graalvm/setup-graalvm
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: mvn -Pnative -DskipTests package
    - uses: actions/upload-artifact@v3
      with:
        name: krt-native-image-${{ matrix.os }}
        path: target/krt
  krt-native-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - uses: ilammy/msvc-dev-cmd@v1 # https://github.com/ilammy/msvc-dev-cmd
    - uses: graalvm/setup-graalvm@v1 # https://github.com/graalvm/setup-graalvm
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: mvn -Pnative -DskipTests package
    - uses: actions/upload-artifact@v3
      with:
        name: krt-native-image-windows-latest
        path: target/krt.exe
