name: Release yak4j-sync-archetype-maven-plugin

on:
  push:
    tags: [ "plugins/yak4j-sync-archetype-maven-plugin/v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build arturito release tooling
      run: mvn -B -ntp --file internal-tooling/arturito/pom.xml package
    - name: Run arturito release tooling
      run: >-
        cd plugins/yak4j-sync-archetype-maven-plugin && java -jar ../../internal-tooling/arturito/target/arturito-1.0-SNAPSHOT.jar
        ${{ secrets.GPG_KEY }}
        ${{ secrets.GPG_PASSPHRASE }}
        ${{ secrets.OSSRH_USERNAME }}
        ${{ secrets.OSSRH_PASSWORD }}
